### ISSUE TITLE
stylesheet lowercases all xlink: attributes including href: breaks links

### ISSUE THREAD

**Issue by sdm7g** [SAA-SDT/EAD2002toEAD3#48]
The stylesheet appears to break xlink:href attributes by lowercasing their values:

https://github.com/SAA-SDT/EAD2002toEAD3/blob/master/xslt/EAD2002ToEAD3.xsl#L1845

**Comment by rockivist** [comment]
@sdm7g Thanks for catching this. I have a few other changes to make and will fold this in. In the meantime, simply changing `<xsl:value-of select="normalize-space(lower-case(.))"/>` to `<xsl:value-of select="normalize-space(.)"/>` should fix the issue.

**Comment by rockivist** [comment]
Fixed by modifying the xlink stripping template, adding xsl:choose so that href attributes are not converted to lowercase.
