### ISSUE TITLE
/chronitem/date without @normal doesn't seem to be handled right

### ISSUE THREAD

**Issue by ruthtillman** [SAA-SDT/EAD2002toEAD3#54]
We have instances of chronitem as

```
<chronitem>
  <date>1854-1911</date>
  <event>St. Patrick's School operates, Louisville, KY</event>
</chronitem>
```

being returned as

```
<chronitem>
  <datesingle>1854-1911</datesingle>
  <event>St. Patrick's School operates, Louisville, KY</event>
</chronitem>
```

Is there a way to test  the content itself for the - or is that too edge a case? (I didn't get in-depth with the stylesheet here, sorry busy morning, but I got the impression the primary tests were of `@normal` vs. content itself)

**Comment by rockivist** [comment]
@ruthtillman As I recall you are correct - within chronitem, when dates lack the normal attribute, they migrate as datesingle. I didn't think parsing the text using XSLT was a great idea. Doable, but might create more problems than it solves.

**Comment by ruthtillman** [comment]
That makes sense, as it could get wonky. Perhaps I'll try a local fork and see what happens.
